This is the first task

In [1]:
# pip install pandas
# pip install requests




In [2]:
import pandas as pd
import numpy as np


In [3]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print("Numpy Array:", arr)

Numpy Array: [1 2 3 4 5]


In [4]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_arr = np.array(my_matrix)

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros((3, 4)) # 3 rows, 4 columns
np.ones((2, 5)) # 2 rows, 5 columns
np.linspace(0, 1, 5) # 5 values between 0 and 1
np.eye(4) # 4x4 Identity matrix
np.random.rand(3, 3) #
np.random.randint(1, 100, size=(4, 4))   # inclusive of low, exclusive of high
np.random.seed(42) # for reproducibility
np.random.randn(2, 2) # standard normal distribution


array([[ 0.49671415, -0.1382643 ],
       [ 0.64768854,  1.52302986]])

In [7]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
arr = np.arange(25).reshape(5, 5)
arr.sum() # total sum
arr.sum(axis=1) # row-wise sum          
arr.sum(axis=0) # column-wise sum   
arr.mean() # average
arr.std()  # standard deviation         
arr.max()  # maximum value
arr.min() # minimum value
arr.argmax() # index of max value   
arr.argmin() # index of min value


np.int64(0)

In [9]:
# arr.argmax() # index of max value
# arr.argmin() # index of min value
# arr.shape # dimensions of the array
# arr.reshape(25, 1) # reshape to 25 rows, 1 column   
# arr.reshape(1, 25) # reshape to 1 row, 25 columns
# arr.T # transpose of the array
# arr_flat = arr.flatten() # flatten the array
# arr_flat.reshape(5, 5) # reshape back to 5x5    
arr_slice = arr[1:4, 1:4] # slicing the array
# arr_slice[0, 0] = 99 # modifying an element
# arr_slice
# arr.dtype # data type of the array elements
# arr.astype('float32') # changing data type to float32
# arr_copy = arr.copy() # creating a copy of the array
arr_slice

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [10]:
arr[0]

array([0, 1, 2, 3, 4])

In [18]:
# write a function that will double the following numbers and store them in another variable double
df = pd.DataFrame({'number': [1,2,3,4,5]})

def double_double(x):
    d = x * 2
    return d

df['double'] = df['number'].apply(double_double)
#df
print(df)
#display(df)

   number  double
0       1       2
1       2       4
2       3       6
3       4       8
4       5      10


In [24]:
# Make a function that returns "Even" or "Odd", then apply it

df = pd.DataFrame({'value': [10, 15, 22, 7, 3]})

def even_odd(x):
    if x % 2 == 0:
        return "even"
    else:
        return "odd"
    
df['doub'] = df['value'].apply(double_double)
df['checkeven'] = df['value'].apply(even_odd)
df


value  doub checkeven
0     10    20      even
1     15    30       odd
2     22    44      even
3      7    14       odd
4      3     6       odd

In [ ]:
# Work with text — make everything uppercase after you must have stripped all the unnessesary spaces

df_g = pd.DataFrame({'name': ['alice ', ' bob ', 'cha rlie ', ' dave ']})
df_g

def make_upper(x):
    a = x.strip().upper().replace(" ", "")
    return a

df_g['namee'] = df_g['name'].apply(make_upper)
df_g

name    namee
0     alice     ALICE
1       bob       BOB
2  cha rlie   CHARLIE
3      dave      DAVE

In [30]:
# Grade Calculator

df = pd.DataFrame({'score': [95, 82, 75, 60, 45, 88]})

def get_grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    elif score >= 60:
        return "D"
    else: 
        return "F"
    
df['grade'] = df['score'].apply(get_grade)
df

score grade
0     95     A
1     82     B
2     75     C
3     60     D
4     45     F
5     88     B

In [32]:
# Categorize Age Groups
df = pd.DataFrame({'age': [12, 17, 25, 45, 67, 8, 33]})

def age_group(age):
    if age < 13:
        return "Child"
    elif 13 <= age < 18:
        return "Teen"
    elif 18 <= age < 65:
        return "Adult" 
    elif age >= 65:
        return "Senior"
    else: 
        return None
df['category'] =  df['age'].apply(age_group)
df


age category
0   12    Child
1   17     Teen
2   25    Adult
3   45    Adult
4   67   Senior
5    8    Child
6   33    Adult

In [47]:
# Extract First Letter of Each Word

df = pd.DataFrame({'full_name': ['John Doe', 'Alice Smith', 'Bob Johnson', 'Eve Brown']})

def get_initials(name):
    parts = name.split()
    return ".".join(p[0].upper() for p in parts)

df['initials'] = df['full_name'].apply(get_initials)
df



full_name initials
0     John Doe      J.D
1  Alice Smith      A.S
2  Bob Johnson      B.J
3    Eve Brown      E.B